### ISSUE TITLE
Add a button to show each person's intro video

### ISSUE THREAD

**Issue by IsmailM** [PGP-UK/GenoME#139]
Add as an icon before Ancestry - labelled as 'My Story'

**Comment by IsmailM** [comment]
I would add a separate section on this - above the 'tap below to explore a few of my variants...'

I would have a button with a white border and no background, that has an icon, And 'My Story' inside the button,

This would take you to a new page showing the intro video... 

The icon could either be the person's profile pic - OR something like:

- https://fontawesome.com/icons/chalkboard-user?f=classic&s=duotone
- https://fontawesome.com/icons/address-book?f=classic&s=duotone
- https://fontawesome.com/icons/file-user?f=classic&s=duotone
- https://fontawesome.com/icons/address-card?f=classic&s=duotone
- https://fontawesome.com/icons/chart-user?f=classic&s=duotone
-

**Comment by E-gonito** [comment]
Intro videos can be found https://github.com/PGP-UK/GenoME-iPad/tree/main/GenoME/Videos
