### ISSUE TITLE
Landing page text not always fitting on a single line 

### ISSUE THREAD

**Issue by IsmailM** [PGP-UK/GenoME#153]
E.g. Huawei P20 Pro 

![WhatsApp Image 2022-12-09 at 10 41 18](https://user-images.githubusercontent.com/5578375/206684399-d6af0dec-7918-4ca1-b791-f967b19fd5de.jpg)

**Comment by IsmailM** [comment]
another example: 
![image](https://user-images.githubusercontent.com/5578375/206688218-fab75bcd-778f-44b6-9d48-1d7b26d4daf6.png)

**Comment by NateCreedDonato** [comment]
Issue fixed
